import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar/page";
import Footer from "./_components/Footer/page";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* All Plugins */}
        <link href="/assets/css/bootstrap.min.css" rel="stylesheet" />
        <link href="/assets/css/animation.css" rel="stylesheet" />
        <link href="/assets/css/dropzone.min.css" rel="stylesheet" />
        <link href="/assets/css/flatpickr.min.css" rel="stylesheet" />
        <link href="/assets/css/flickity.min.css" rel="stylesheet" />
        <link href="/assets/css/lightbox.min.css" rel="stylesheet" />
        <link href="/assets/css/magnifypopup.css" rel="stylesheet" />
        <link href="/assets/css/select2.min.css" rel="stylesheet" />
        <link href="/assets/css/rangeSlider.min.css" rel="stylesheet" />
        <link href="/assets/css/prism.css" rel="stylesheet" />

        {/* Font Awsome & Bootstrap css */}
        <link href="/assets/css/bootstrap-icons.css" rel="stylesheet" />
        <link href="/assets/css/fontawesome.css" rel="stylesheet" />

        {/* Custom Css */}
        <link href="/assets/css/style.css" rel="stylesheet" />
      </head>
      <body className={inter.className}>
        {/* <div className="top_contact_bar" >
          <div className="contact_info" >
            <p>24*7 support : <a href="tel:+1-(888) 267-5955" >+1-(888) 267-5955</a></p>
          </div>
        </div> */}
        <div id="main-wrapper" >
          <Navbar />
          <ToastContainer />
          <div className="clearfix"></div>
          {children}
          {/* <!-- All Jquery --> */}
          {/* <!-- ============================================================== --> */}
          <script src="assets/js/jquery.min.js"></script>
          <script src="assets/js/popper.min.js"></script>
          <script src="assets/js/bootstrap.min.js"></script>
          <script src="assets/js/dropzone.min.js"></script>
          <script src="assets/js/flatpickr.js"></script>
          {/* <Script src="assets/js/flickity.pkgd.min.js" strategy="lazyOnload" /> */}
          {/* <script src="assets/js/flickity.pkgd.min.js"></script> */}
          <script src="assets/js/lightbox.min.js"></script>
          <script src="assets/js/rangeslider.js"></script>
          <script src="assets/js/select2.min.js"></script>
          <script src="assets/js/counterup.min.js"></script>
          <script src="assets/js/prism.js"></script>

          {/* <script src="assets/js/addadult.js"></script> */}
          {/* <script src="assets/js/custom.js"></script> */}
          {/* <!-- ============================================================== -->
  <!-- This page plugins -->
  <!-- ============================================================== --> */}
        </div>
        <Footer />
      </body>
    </html>
  );
}
